// Password hashing (port of pkg/auth/password.go).
//
// Go uses golang.org/x/crypto/bcrypt at DefaultCost (cost 10). bcryptjs is a
// pure-JS port of the same algorithm and produces cross-compatible hashes, so
// hashes generated by the Go binary remain verifiable here and vice-versa.

import bcrypt from 'bcryptjs';

/** bcrypt cost — Go's bcrypt.DefaultCost is 10. */
const COST = 10;

/** Hash a plaintext password. Mirrors auth.HashPassword (DefaultCost). */
export async function hashPassword(plain: string): Promise<string> {
  // bcryptjs.hash is async (yields to the event loop); the sync variant
  // (hashSync) would block the Workers event loop, so prefer the async form.
  return bcrypt.hash(plain, COST);
}

/** Constant-time compare of plaintext against a bcrypt hash. Mirrors auth.CheckPassword. */
export async function comparePassword(plain: string, hash: string): Promise<boolean> {
  try {
    return await bcrypt.compare(plain, hash);
  } catch {
    // Malformed hash → treat as no match, matching Go's CompareHashAndPassword
    // error semantics (err != nil → false).
    return false;
  }
}
